export const initialState = {
  user: false,
  authdialog: { open: false, login: true },
  currentDocumentationTab: { value: "Знакомство", index: 0 },
  addMerchant: {
    name: "",
    domain: "",
    country: 1,
    city: "",
    organization_type: 1,
    legal_name: "",
    activity_type: 1,
    company_reg_date: "",
    inn: "",
    okpo: "",
    bik: "",
    bank_name: "",
    checking_account: "",
    iban: "",
    decisions: "",
    charter: "",
    certificate: "",
    upload_file: "",
  },
  alert: {
    open: false,
    severity: "success",
    message: "This is a success message!",
  },
};
