export const initialState = {
  user: false,
  authdialog: { open: false, login: true },
  openBackdrop: false,
  currentDocumentationTab: { value: "Знакомство", index: 0 },
  merchants: "",
  balance: "",
  statistics: {},
  addMerchant: {
    name: "Netex",
    domain: "netex.kz",
    country: 1,
    city: "Bishkek",
    organization_type: 1,
    legal_name: "Netex OZ",
    activity_type: 1,
    company_reg_date: "",
    inn: "inn",
    okpo: "okpo",
    bik: "bik",
    bank_name: "bank",
    checking_account: "12121212",
    iban: "iban",
    decisions: "",
    charter: "",
    certificate: "",
    upload_file: "",
  },
  filesToUpload: {},
  profileInfo: "",
  token: "",
  alert: {
    open: false,
    severity: "success",
    message: "This is a success message!",
  },
};
